# Use kubectl apply -f api-url-secret.yaml -n <NAMESPACE> fore each namespace to make sure that the pods can read the secrets
#NEVER COMMIT THIS FILE TO A GIT REPO!!!
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-url  
type: Opaque
stringData:
  WEAVIATE_URL: please enter weaviate url
---

apiVersion: v1
kind: Secret
metadata:
  name: s3-endpoint-url 
type: Opaque
stringData:
  S3_ENDPOINT_URL: please enter s3 eindpoint url
---

apiVersion: v1
kind: Secret
metadata:
  name: worker-url 
type: Opaque
stringData:
  WORKER_URL: please enter worker url
---

apiVersion: v1
kind: Secret
metadata:
  name: aws-access-key-id 
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: please enter minio access key id
---

apiVersion: v1
kind: Secret
metadata:
  name: aws-secret-access-key  
type: Opaque
stringData:
  AWS_SECRET_ACCESS_KEY: please enter minio access key 
---

apiVersion: v1
kind: Secret
metadata:
  name: cohere-api-key 
type: Opaque
stringData:
  COHERE_API_KEY: enter you generated api key here
---

apiVersion: v1
kind: Secret
metadata:
  name: api-url 
type: Opaque
stringData:
  API_URL: entere the api endpoint url
---

apiVersion: v1
kind: Secret
metadata:
  name: minio-root-user 
type: Opaque
stringData:
  MINIO_ROOT_USER: enter strong minio username
---

apiVersion: v1
kind: Secret
metadata:
  name: minio-root-password 
type: Opaque
stringData:
  MINIO_ROOT_PASSWORD:  enter strong minio username
---



  